name: Super linter

on:
  pull_request:
    branches:
      - "**"
      
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📜 Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: 🛠️ Set up Flutter
        run: flutter pub get
        
      - name: 🧑‍💻 Generate files with Builder
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: 🤖 Task Force Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "github_actions"
